### PR TITLE
fix(db): preserve rollback after SQLite invalidation

### PR DESCRIPTION
**Pull request by NikitaMGrimm**
## Summary

SQLite watchdog callbacks read Connection.info during rollback. If the transaction's connection was invalidated, that read attempts to reconnect and raises PendingRollbackError before rollback can finish. Skip diagnostic metadata reads on invalidated or closed connections so rollback and subsequent queries succeed.

This is the independent database fix extracted from #1528 at the maintainer's suggestion. It does not implement the usage-limit feature or close its issue.

## Changes

- Guard the watchdog's connection metadata reads.
- Retain the invalidation/rollback regression from #1528.
- Allow existing failed-teardown tests to observe a closed connection after successful cleanup, while preserving session-fencing assertions.
- Preserve contributor attribution.

## OpenSpec

openspec/changes/fix-sqlite-watchdog-rollback/

## Validation

- Reproduced PendingRollbackError against unchanged upstream e987c56c85a3dc516e6a543ff13a9513ca41aafb.
- All 86 database-session tests pass with the fix.
- Ruff, formatting, type checks, cancellation/timing checks, contributor coverage, simplicity budgets, and strict OpenSpec validation pass.
- No schema, configuration, or UI changes.
- Remote CI has not yet run.

### CODE REVIEW

**Comment by Komzpa** [comment]
@codex review
